version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with clang
          command: USE_CURL=1 sh ci/linux.sh clang_build
      - store_artifacts:
          path: build/output/libNFDecoder.zip
          destination: libNFDecoder.zip
  buildlinuxgcc:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with gcc
          command: USE_CURL=1 sh ci/linux.sh gcc_build
      - store_artifacts:
          path: build/output/libNFDecoder.zip
          destination: libNFDecoder.zip
  buildlinuxandroid:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 USE_CURL=1 sh ci/linux.sh build
      - store_artifacts:
          path: libNFDecoder-androidx86.zip
          destination: libNFDecoder-androidx86.zip
      - store_artifacts:
          path: libNFDecoder-androidArm64.zip
          destination: libNFDecoder-androidArm64.zip
  buildmac:
    macos:
      xcode: "11.5.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew update
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build OSX
          command: USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFDecoder.zip
          destination: libNFDecoder.zip
  buildmacios:
    macos:
      xcode: "11.5.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew update
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Build iOS
          command: BUILD_IOS=1 USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFDecoder.zip
          destination: libNFDecoder.zip
  buildmacandroid:
    macos:
      xcode: "11.5.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew update
      - run: git submodule sync
      - run: git submodule update --init --recursive
      # Android NDK does not pass.
      - run: sudo spctl --master-disable
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 USE_CURL=1 sh ci/osx.sh build
      - store_artifacts:
          path: libNFDecoder-androidx86.zip
          destination: libNFDecoder-androidx86.zip
      - store_artifacts:
          path: libNFDecoder-androidArm64.zip
          destination: libNFDecoder-androidArm64.zip
workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildlinuxgcc
      - buildlinuxandroid
      - buildmac
      - buildmacios
      - buildmacandroid
